apiVersion: v1
kind: Service
metadata:
  name: registration-application-service
  labels:
    app: registration-application
spec:
  selector:
    app: registration-application

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
